# Generated by Django 5.1.7 on 2025-04-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_riskevaluation_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskevaluation',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='riesgos/'),
        ),
    ]
